/** @file cmdline.h
 *  @brief The header file for the command line option parser
 *  generated by GNU Gengetopt version 2.22.6
 *  http://www.gnu.org/software/gengetopt.
 *  DO NOT modify this file, since it can be overwritten
 *  @author GNU Gengetopt by Lorenzo Bettini */

#ifndef CMDLINE_H
#define CMDLINE_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h> /* for FILE */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
/** @brief the program name (used for printing errors) */
#define CMDLINE_PARSER_PACKAGE "histomode"
#endif

#ifndef CMDLINE_PARSER_PACKAGE_NAME
/** @brief the complete program name (used for help and version) */
#define CMDLINE_PARSER_PACKAGE_NAME "histomode"
#endif

#ifndef CMDLINE_PARSER_VERSION
/** @brief the program version */
#define CMDLINE_PARSER_VERSION "0.1"
#endif

/** @brief Where the command line options are stored */
struct gengetopt_args_info
{
  const char *help_help; /**< @brief Print help and exit help description.  */
  const char *version_help; /**< @brief Print version and exit help description.  */
  char * Filename_arg;	/**< @brief Output filename (default='stdout').  */
  char * Filename_orig;	/**< @brief Output filename original value given at command line.  */
  const char *Filename_help; /**< @brief Output filename help description.  */
  float Duration_arg;	/**< @brief Duration of acquisition (second) (default='1').  */
  char * Duration_orig;	/**< @brief Duration of acquisition (second) original value given at command line.  */
  const char *Duration_help; /**< @brief Duration of acquisition (second) help description.  */
  int Binning_arg;	/**< @brief Binning (default='0').  */
  char * Binning_orig;	/**< @brief Binning original value given at command line.  */
  const char *Binning_help; /**< @brief Binning help description.  */
  int SyncDivider_arg;	/**< @brief Sync Divider (default='1').  */
  char * SyncDivider_orig;	/**< @brief Sync Divider original value given at command line.  */
  const char *SyncDivider_help; /**< @brief Sync Divider help description.  */
  int SyncCFDZeroCross_arg;	/**< @brief SyncCFDZeroCross (default='10').  */
  char * SyncCFDZeroCross_orig;	/**< @brief SyncCFDZeroCross original value given at command line.  */
  const char *SyncCFDZeroCross_help; /**< @brief SyncCFDZeroCross help description.  */
  int SyncCFDLevel_arg;	/**< @brief Sync CFD Level (default='50').  */
  char * SyncCFDLevel_orig;	/**< @brief Sync CFD Level original value given at command line.  */
  const char *SyncCFDLevel_help; /**< @brief Sync CFD Level help description.  */
  int SyncChannelOffset_arg;	/**< @brief Sync Channel Offset (default='0').  */
  char * SyncChannelOffset_orig;	/**< @brief Sync Channel Offset original value given at command line.  */
  const char *SyncChannelOffset_help; /**< @brief Sync Channel Offset help description.  */
  int InputCFDZeroCross_arg;	/**< @brief Input CFD Zero Cross (default='10').  */
  char * InputCFDZeroCross_orig;	/**< @brief Input CFD Zero Cross original value given at command line.  */
  const char *InputCFDZeroCross_help; /**< @brief Input CFD Zero Cross help description.  */
  int InputCFDLevel_arg;	/**< @brief Input CFD Level (default='50').  */
  char * InputCFDLevel_orig;	/**< @brief Input CFD Level original value given at command line.  */
  const char *InputCFDLevel_help; /**< @brief Input CFD Level help description.  */
  int InputChannelOffset_arg;	/**< @brief Input Channel Offset (default='0').  */
  char * InputChannelOffset_orig;	/**< @brief Input Channel Offset original value given at command line.  */
  const char *InputChannelOffset_help; /**< @brief Input Channel Offset help description.  */
  
  unsigned int help_given ;	/**< @brief Whether help was given.  */
  unsigned int version_given ;	/**< @brief Whether version was given.  */
  unsigned int Filename_given ;	/**< @brief Whether Filename was given.  */
  unsigned int Duration_given ;	/**< @brief Whether Duration was given.  */
  unsigned int Binning_given ;	/**< @brief Whether Binning was given.  */
  unsigned int SyncDivider_given ;	/**< @brief Whether SyncDivider was given.  */
  unsigned int SyncCFDZeroCross_given ;	/**< @brief Whether SyncCFDZeroCross was given.  */
  unsigned int SyncCFDLevel_given ;	/**< @brief Whether SyncCFDLevel was given.  */
  unsigned int SyncChannelOffset_given ;	/**< @brief Whether SyncChannelOffset was given.  */
  unsigned int InputCFDZeroCross_given ;	/**< @brief Whether InputCFDZeroCross was given.  */
  unsigned int InputCFDLevel_given ;	/**< @brief Whether InputCFDLevel was given.  */
  unsigned int InputChannelOffset_given ;	/**< @brief Whether InputChannelOffset was given.  */

} ;

/** @brief The additional parameters to pass to parser functions */
struct cmdline_parser_params
{
  int override; /**< @brief whether to override possibly already present options (default 0) */
  int initialize; /**< @brief whether to initialize the option structure gengetopt_args_info (default 1) */
  int check_required; /**< @brief whether to check that all required options were provided (default 1) */
  int check_ambiguity; /**< @brief whether to check for options already specified in the option structure gengetopt_args_info (default 0) */
  int print_errors; /**< @brief whether getopt_long should print an error message for a bad option (default 1) */
} ;

/** @brief the purpose string of the program */
extern const char *gengetopt_args_info_purpose;
/** @brief the usage string of the program */
extern const char *gengetopt_args_info_usage;
/** @brief the description string of the program */
extern const char *gengetopt_args_info_description;
/** @brief all the lines making the help output */
extern const char *gengetopt_args_info_help[];

/**
 * The command line parser
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser (int argc, char **argv,
  struct gengetopt_args_info *args_info);

/**
 * The command line parser (version with additional parameters - deprecated)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param override whether to override possibly already present options
 * @param initialize whether to initialize the option structure my_args_info
 * @param check_required whether to check that all required options were provided
 * @return 0 if everything went fine, NON 0 if an error took place
 * @deprecated use cmdline_parser_ext() instead
 */
int cmdline_parser2 (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  int override, int initialize, int check_required);

/**
 * The command line parser (version with additional parameters)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param params additional parameters for the parser
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_ext (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  struct cmdline_parser_params *params);

/**
 * Save the contents of the option struct into an already open FILE stream.
 * @param outfile the stream where to dump options
 * @param args_info the option struct to dump
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_dump(FILE *outfile,
  struct gengetopt_args_info *args_info);

/**
 * Save the contents of the option struct into a (text) file.
 * This file can be read by the config file parser (if generated by gengetopt)
 * @param filename the file where to save
 * @param args_info the option struct to save
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_file_save(const char *filename,
  struct gengetopt_args_info *args_info);

/**
 * Print the help
 */
void cmdline_parser_print_help(void);
/**
 * Print the version
 */
void cmdline_parser_print_version(void);

/**
 * Initializes all the fields a cmdline_parser_params structure 
 * to their default values
 * @param params the structure to initialize
 */
void cmdline_parser_params_init(struct cmdline_parser_params *params);

/**
 * Allocates dynamically a cmdline_parser_params structure and initializes
 * all its fields to their default values
 * @return the created and initialized cmdline_parser_params structure
 */
struct cmdline_parser_params *cmdline_parser_params_create(void);

/**
 * Initializes the passed gengetopt_args_info structure's fields
 * (also set default values for options that have a default)
 * @param args_info the structure to initialize
 */
void cmdline_parser_init (struct gengetopt_args_info *args_info);
/**
 * Deallocates the string fields of the gengetopt_args_info structure
 * (but does not deallocate the structure itself)
 * @param args_info the structure to deallocate
 */
void cmdline_parser_free (struct gengetopt_args_info *args_info);

/**
 * Checks that all the required options were specified
 * @param args_info the structure to check
 * @param prog_name the name of the program that will be used to print
 *   possible errors
 * @return
 */
int cmdline_parser_required (struct gengetopt_args_info *args_info,
  const char *prog_name);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* CMDLINE_H */
